package com.richardtalcott.periodic;

public final class ElementData {
 public final int number,row,group,period,estimatedNeutrons;
 public final String symbol,name,category,atomicMass;
 private ElementData(int n,String s,String nm,int r,int g,String c){number=n;symbol=s;name=nm;row=r;group=g;period=Math.min(r,7);category=c;int mass=Math.max(n,Math.round(n*2.35f));atomicMass="~"+mass;estimatedNeutrons=mass-n;}
 private static final String[] SYMBOLS="H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr Rf Db Sg Bh Hs Mt Ds Rg Cn Nh Fl Mc Lv Ts Og".split(" ");
 private static final String[] NAMES="Hydrogen|Helium|Lithium|Beryllium|Boron|Carbon|Nitrogen|Oxygen|Fluorine|Neon|Sodium|Magnesium|Aluminium|Silicon|Phosphorus|Sulfur|Chlorine|Argon|Potassium|Calcium|Scandium|Titanium|Vanadium|Chromium|Manganese|Iron|Cobalt|Nickel|Copper|Zinc|Gallium|Germanium|Arsenic|Selenium|Bromine|Krypton|Rubidium|Strontium|Yttrium|Zirconium|Niobium|Molybdenum|Technetium|Ruthenium|Rhodium|Palladium|Silver|Cadmium|Indium|Tin|Antimony|Tellurium|Iodine|Xenon|Caesium|Barium|Lanthanum|Cerium|Praseodymium|Neodymium|Promethium|Samarium|Europium|Gadolinium|Terbium|Dysprosium|Holmium|Erbium|Thulium|Ytterbium|Lutetium|Hafnium|Tantalum|Tungsten|Rhenium|Osmium|Iridium|Platinum|Gold|Mercury|Thallium|Lead|Bismuth|Polonium|Astatine|Radon|Francium|Radium|Actinium|Thorium|Protactinium|Uranium|Neptunium|Plutonium|Americium|Curium|Berkelium|Californium|Einsteinium|Fermium|Mendelevium|Nobelium|Lawrencium|Rutherfordium|Dubnium|Seaborgium|Bohrium|Hassium|Meitnerium|Darmstadtium|Roentgenium|Copernicium|Nihonium|Flerovium|Moscovium|Livermorium|Tennessine|Oganesson".split("\\|");
 public static ElementData byNumber(int n){n=Math.max(1,Math.min(118,n));int[] pos=position(n);return new ElementData(n,SYMBOLS[n-1],NAMES[n-1],pos[0],pos[1],category(n,pos[1]));}
 public static ElementData find(String q){if(q==null)return null;q=q.trim();try{return byNumber(Integer.parseInt(q));}catch(Exception ignored){}for(int i=0;i<118;i++)if(SYMBOLS[i].equalsIgnoreCase(q)||NAMES[i].equalsIgnoreCase(q))return byNumber(i+1);return null;}
 private static int[] position(int n){if(n==1)return new int[]{1,1};if(n==2)return new int[]{1,18};if(n<=10){int[]g={1,2,13,14,15,16,17,18};return new int[]{2,g[n-3]};}if(n<=18){int[]g={1,2,13,14,15,16,17,18};return new int[]{3,g[n-11]};}if(n<=36)return new int[]{4,n-18};if(n<=54)return new int[]{5,n-36};if(n==55)return new int[]{6,1};if(n==56)return new int[]{6,2};if(n>=57&&n<=71)return new int[]{8,n-54};if(n<=86)return new int[]{6,n-68};if(n==87)return new int[]{7,1};if(n==88)return new int[]{7,2};if(n>=89&&n<=103)return new int[]{9,n-86};return new int[]{7,n-100};}
 private static String category(int n,int g){if(n>=57&&n<=71)return"Lanthanide";if(n>=89&&n<=103)return"Actinide";if(g==18)return"Noble gas";if(g==17)return"Halogen";if(g==1&&n!=1)return"Alkali metal";if(g==2)return"Alkaline-earth metal";if(g>=3&&g<=12)return"Transition metal";if(n==1||n==6||n==7||n==8||n==15||n==16||n==34)return"Nonmetal";if(n==5||n==14||n==32||n==33||n==51||n==52)return"Metalloid";return"Post-transition / synthetic";}
 public static int[] shells(int n){int[] caps={2,8,18,32,32,18,8};int[] out=new int[7];int left=n;for(int i=0;i<caps.length&&left>0;i++){out[i]=Math.min(caps[i],left);left-=out[i];}return out;}
}