package com.richardtalcott.periodic

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.compose.BackHandler
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.view.WindowInsetsControllerCompat
import androidx.compose.animation.AnimatedContent
import androidx.compose.animation.core.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlin.math.*

class MainActivity : ComponentActivity() {
  override fun onCreate(state: Bundle?) {
    super.onCreate(state)
    WindowCompat.setDecorFitsSystemWindows(window,false)
    WindowInsetsControllerCompat(window,window.decorView).apply {
      hide(WindowInsetsCompat.Type.systemBars())
      systemBarsBehavior=WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
    }
    setContent { Studio() }
  }
}
private val Ink=Color(0xFF020711); private val Panel=Color(0xD9071827); private val Cyan=Color(0xFF52D7FF)
private val Gold=Color(0xFFFFC768); private val Red=Color(0xFFFF557F); private val Blue=Color(0xFF639EFF)
private enum class Page(val title:String){TABLE("Periodic Table"),INFO("Element Information"),ATOM("Atom Explorer"),ISOTOPE("Isotope Lab"),ION("Ion Builder"),BOND("Bond Builder"),STATES("States of Matter Lab"),COMPARE("Compare Elements")}
private data class Element(val n:Int,val symbol:String,val name:String,val row:Int,val col:Int,val mass:Int,val kind:Int)
private val symbols="H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr Rf Db Sg Bh Hs Mt Ds Rg Cn Nh Fl Mc Lv Ts Og".split(" ")
private fun pos(n:Int)=when{n==1->1 to 1;n==2->1 to 18;n<=10->2 to listOf(1,2,13,14,15,16,17,18)[n-3];n<=18->3 to listOf(1,2,13,14,15,16,17,18)[n-11];n<=36->4 to n-18;n<=54->5 to n-36;n==55->6 to 1;n==56->6 to 2;n in 57..71->8 to n-54;n<=86->6 to n-68;n==87->7 to 1;n==88->7 to 2;n in 89..103->9 to n-86;else->7 to n-100}
private fun all()=(1..118).map{n->val p=pos(n);Element(n,symbols[n-1],ELEMENT_NAMES[n-1],p.first,p.second,REPRESENTATIVE_MASS_NUMBERS[n-1],when{n in 57..71->5;n in 89..103->6;p.second==18->4;p.second==17->3;p.second in 3..12->2;else->1})}

@Composable private fun Studio(){var page by remember{mutableStateOf(Page.TABLE)};var selected by remember{mutableStateOf(all()[25])};var compare by remember{mutableStateOf(all()[28])};BackHandler(enabled=page!=Page.TABLE){page=if(page==Page.INFO)Page.TABLE else Page.INFO};MaterialTheme(colorScheme=darkColorScheme(primary=Cyan,background=Ink,surface=Panel,onBackground=Color.White,onSurface=Color.White)){CompositionLocalProvider(LocalContentColor provides Color.White){Box(Modifier.fillMaxSize().safeDrawingPadding().background(Ink)){ReactorBackdrop();Stars();AnimatedContent(page,label="page"){p->when(p){Page.TABLE->Table{selected=it;page=Page.INFO};Page.INFO->Info(selected,{page=Page.TABLE}){page=it};Page.ATOM->AtomExplorer(selected){page=Page.INFO};Page.ISOTOPE->Isotope(selected){page=Page.INFO};Page.ION->Ion(selected){page=Page.INFO};Page.BOND->Bond{page=Page.INFO};Page.STATES->States{page=Page.INFO};Page.COMPARE->Compare(selected,compare,{compare=it}){page=Page.INFO}}}}}}}
@Composable private fun Stars(){Canvas(Modifier.fillMaxSize()){repeat(90){i->drawCircle(Color.White.copy(.12f+(i%5)*.05f),1f+(i%3),Offset(((i*83)%997)/997f*size.width,((i*137)%991)/991f*size.height))}}}
@Composable private fun ReactorBackdrop(){Canvas(Modifier.fillMaxSize()){drawRect(Brush.verticalGradient(listOf(Color(0xFF03101A),Color(0xFF071D2D),Ink)));val horizon=size.height*.72f;repeat(12){i->val x=size.width*i/11f;drawLine(Cyan.copy(.09f),Offset(size.width/2,horizon),Offset(x,size.height),1f)};repeat(5){i->drawOval(Cyan.copy(.08f),topLeft=Offset(-size.width*.1f,horizon+i*38f),size=androidx.compose.ui.geometry.Size(size.width*1.2f,70f+i*20f),style=Stroke(2f))};repeat(9){i->val x=size.width*i/8f;drawRect(Brush.horizontalGradient(listOf(Color.Transparent,Cyan.copy(.08f),Color.Transparent)),Offset(x-35f,0f),androidx.compose.ui.geometry.Size(70f,horizon))};drawLine(Cyan.copy(.18f),Offset(0f,horizon),Offset(size.width,horizon),3f)}}
@Composable private fun Header(title:String,sub:String,back:(()->Unit)?=null){Row(Modifier.fillMaxWidth().padding(18.dp),verticalAlignment=Alignment.CenterVertically){if(back!=null)OutlinedButton(back){Text("‹ Back")};Column(Modifier.padding(start=16.dp)){Text(title.uppercase(),fontSize=26.sp,fontWeight=FontWeight.Black);Text(sub,fontSize=12.sp,color=Cyan)}}}
private fun color(k:Int)=listOf(Color.Gray,Color(0xFF27A88B),Color(0xFF2C9EC8),Color(0xFF9B4AA5),Color(0xFF386FC0),Color(0xFF8B55C7),Color(0xFFC34B87))[k]
@Composable private fun Table(open:(Element)->Unit){Column(Modifier.fillMaxSize()){
 Row(Modifier.fillMaxWidth().padding(start=28.dp,top=16.dp,end=28.dp,bottom=6.dp),verticalAlignment=Alignment.CenterVertically){Column{Text("PERIODIC",fontSize=30.sp,fontWeight=FontWeight.Black,letterSpacing=2.sp);Text("EXPLORE THE ELEMENTS",fontSize=12.sp,color=Cyan)};Spacer(Modifier.weight(1f));Text("118 ELEMENTS  •  TAP TO EXPLORE",fontSize=11.sp,color=Color.White.copy(.7f))}
 BoxWithConstraints(Modifier.fillMaxSize().padding(horizontal=28.dp,vertical=8.dp)){val w=maxWidth/18;val h=maxHeight/9;all().forEach{e->Box(Modifier.offset(w*(e.col-1),h*(e.row-1)).size(w,h).padding(2.dp).background(Brush.verticalGradient(listOf(color(e.kind).copy(.98f),color(e.kind).copy(.72f),Color(0xFF061522))),RoundedCornerShape(7.dp)).border(1.dp,Color.White.copy(.26f),RoundedCornerShape(7.dp)).clickable{open(e)}){Text("${e.n}",fontSize=6.sp,color=Color.White.copy(.74f),modifier=Modifier.align(Alignment.TopStart).padding(start=4.dp,top=2.dp));Column(Modifier.align(Alignment.Center),horizontalAlignment=Alignment.CenterHorizontally){Text(e.symbol,fontSize=15.sp,fontWeight=FontWeight.Black,color=Color.White);Text(e.name.uppercase(),fontSize=4.sp,color=Color.White.copy(.75f),maxLines=1)}}}}
}}
@Composable private fun Glass(mod:Modifier=Modifier,body:@Composable ColumnScope.()->Unit){Column(mod.background(Brush.verticalGradient(listOf(Color(0xED0A2133),Color(0xF0061725),Color(0xF0020A12))),RoundedCornerShape(18.dp)).border(1.dp,Cyan.copy(.42f),RoundedCornerShape(18.dp)).padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.SpaceEvenly,content=body)}
@Composable private fun Metric(label:String,value:String,tint:Color=Cyan){Row(Modifier.fillMaxWidth().padding(vertical=3.dp),horizontalArrangement=Arrangement.SpaceBetween){Text(label.uppercase(),fontSize=9.sp,color=Color.White.copy(.55f));Text(value,fontSize=11.sp,fontWeight=FontWeight.SemiBold,color=tint)}}
@Composable private fun Info(e:Element,back:()->Unit,go:(Page)->Unit){
 val p=ELEMENT_PROPERTIES[e.n-1]
 Column(Modifier.fillMaxSize()){Header("${e.name} (${e.symbol})","ATOMIC NUMBER ${e.n} • ${p.category.uppercase()}",back)
  Row(Modifier.fillMaxSize().padding(24.dp),horizontalArrangement=Arrangement.spacedBy(24.dp)){
   Glass(Modifier.weight(1f).fillMaxHeight()){
    Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("${e.n}",fontSize=18.sp,color=Cyan);Text(p.category.uppercase(),fontSize=11.sp,color=Gold)}
    Text(e.symbol,fontSize=82.sp,fontWeight=FontWeight.Black,color=Color.White);Text(e.name,fontSize=27.sp,color=Color.White)
    HorizontalDivider(color=Cyan.copy(.25f))
    Text("ATOMIC MASS   ${p.atomicMass} u\nDENSITY   ${p.density} g/cm³\nMELTING POINT   ${p.meltingPoint} K\nBOILING POINT   ${p.boilingPoint} K\nELECTRONEGATIVITY   ${p.electronegativity}\nOXIDATION STATES   ${p.oxidationStates}\nELECTRON CONFIGURATION   ${p.configuration}",fontSize=12.sp,lineHeight=17.sp,color=Color.White)
   }
   Glass(Modifier.weight(1.5f).fillMaxHeight()){Box(Modifier.weight(1f).fillMaxWidth()){Atom(e.n);Text("INTERACTIVE ATOM MODEL",Modifier.align(Alignment.TopCenter),fontSize=11.sp,color=Cyan)};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(5.dp)){listOf("ATOM","ISOTOPES","ION","BONDS","MATTER","COMPARE").zip(Page.entries.drop(2)).forEach{(label,target)->OutlinedButton({go(target)},Modifier.weight(1f),contentPadding=PaddingValues(horizontal=3.dp)){Text(label,fontSize=7.sp,color=Color.White,maxLines=1)}}}}
  }
 }
}
@Composable private fun Lab(p:Page,e:Element,back:()->Unit,body:@Composable ()->Unit){Column(Modifier.fillMaxSize()){Header(p.title,"${e.name} • INTERACTIVE SCIENCE LAB",back);Glass(Modifier.fillMaxSize().padding(24.dp)){body()}}}
private val nobleCore=mapOf("He" to 2,"Ne" to 10,"Ar" to 18,"Kr" to 36,"Xe" to 54,"Rn" to 86)
private fun shellCounts(z:Int):List<Int>{
 val counts=IntArray(7);val configuration=ELEMENT_PROPERTIES[z-1].configuration
 Regex("\\[([A-Z][a-z]?)\\]").find(configuration)?.groupValues?.get(1)?.let{core->nobleCore[core]?.let{coreZ->shellCounts(coreZ).forEachIndexed{i,v->counts[i]+=v}}}
 Regex("([1-7])[spdf](\\d+)").findAll(configuration.substringAfter(']',configuration)).forEach{m->counts[m.groupValues[1].toInt()-1]+=m.groupValues[2].toInt()}
 return counts.toList().dropLastWhile{it==0}
}
@Composable private fun Atom(n:Int){val t by rememberInfiniteTransition(label="atom").animateFloat(0f,360f,infiniteRepeatable(tween(9000,easing=LinearEasing)),label="orbit");Canvas(Modifier.fillMaxSize().padding(16.dp)){val c=center;val r=min(size.width,size.height)*.10f;if(n>0){drawCircle(Brush.radialGradient(listOf(Color.White,Red,Color.Transparent),c,r*1.7f),r*1.7f,c);repeat(min(n,54)){i->val a=i*2.399963;val d=r*.12f*sqrt(i.toFloat());drawCircle(if(i%2==0)Red else Blue,r*.13f,Offset(c.x+cos(a).toFloat()*d,c.y+sin(a).toFloat()*d))};val counts=shellCounts(n);counts.forEachIndexed{s,count->val rr=r*(1.65f+s*.62f);drawCircle(Cyan.copy(.30f),rr,c,style=Stroke(2f));repeat(count){i->val direction=if(s%2==0)1 else -1;val a=Math.toRadians((direction*t*(1f+s*.04f)+i*360f/count).toDouble());val p=Offset(c.x+cos(a).toFloat()*rr,c.y+sin(a).toFloat()*rr);drawCircle(Cyan.copy(.18f),13f,p);drawCircle(Color.White,7f,p)}}}}}
@Composable private fun AtomExplorer(e:Element,back:()->Unit){var cloud by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize()){Header("${e.name} (${e.symbol})","ATOM EXPLORER • SCIENTIFICALLY SCALED DIAGRAM",back);Row(Modifier.fillMaxSize().padding(18.dp),horizontalArrangement=Arrangement.spacedBy(16.dp)){Glass(Modifier.width(190.dp).fillMaxHeight()){Text(e.symbol,fontSize=54.sp,fontWeight=FontWeight.Black);Metric("Atomic number","${e.n}");Metric("Protons","${e.n}",Red);Metric("Electrons","${e.n}");Metric("Representative mass","${e.mass} u",Gold);Metric("Neutrons","${e.mass-e.n}",Blue);Text("Shell population\n${shellCounts(e.n).joinToString(" • ")}",fontSize=11.sp,color=Color.White.copy(.8f))};Glass(Modifier.weight(1f).fillMaxHeight()){Box(Modifier.weight(1f).fillMaxWidth()){Atom(e.n);Text(if(cloud)"ELECTRON PROBABILITY CLOUD" else "BOHR SHELL MODEL",Modifier.align(Alignment.TopCenter),fontSize=11.sp,color=Cyan)};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({cloud=false}){Text("Shell model")};OutlinedButton({cloud=true}){Text("Cloud model")};OutlinedButton({}){Text("Pause")}}};Glass(Modifier.width(190.dp).fillMaxHeight()){Text("MODEL NOTES",fontSize=13.sp,color=Cyan);Text("The nucleus is enlarged for visibility. Electron paths depict energy levels, not literal planetary orbits.",fontSize=11.sp,lineHeight=17.sp);HorizontalDivider(color=Cyan.copy(.2f));Metric("Configuration",ELEMENT_PROPERTIES[e.n-1].configuration);Metric("Net charge","0");Metric("Scale","not to scale",Gold)}}}}
@Composable private fun Isotope(e:Element,back:()->Unit){var m by remember{mutableFloatStateOf(e.mass.toFloat())};val neutrons=m.roundToInt()-e.n;Column(Modifier.fillMaxSize()){Header("Isotope Lab","${e.name} • BUILD AND COMPARE ISOTOPES",back);Row(Modifier.fillMaxSize().padding(18.dp),horizontalArrangement=Arrangement.spacedBy(16.dp)){Glass(Modifier.width(210.dp).fillMaxHeight()){Text("ISOTOPE CONTROLS",fontSize=12.sp,color=Cyan);Text("${e.symbol}-${m.roundToInt()}",fontSize=42.sp,color=Gold);Metric("Protons","${e.n}",Red);Metric("Neutrons","$neutrons",Blue);Metric("Mass number","${m.roundToInt()}");Text("Adjust mass number",fontSize=10.sp);Slider(value=m,onValueChange={m=it.roundToInt().toFloat()},valueRange=max(e.n,e.mass-8).toFloat()..(e.mass+8).toFloat(),steps=15)};Glass(Modifier.weight(1f).fillMaxHeight()){Box(Modifier.weight(1f).fillMaxWidth()){Atom(e.n);Text("NUCLEUS: ${e.n}p + ${neutrons}n",Modifier.align(Alignment.TopCenter),color=Cyan,fontSize=11.sp)};Text("Isotopes have the same proton count but different neutron counts.",fontSize=11.sp,color=Color.White.copy(.75f))};Glass(Modifier.width(220.dp).fillMaxHeight()){Text("ISOTOPE INFORMATION",fontSize=12.sp,color=Cyan);Metric("Nuclide","${e.symbol}-${m.roundToInt()}");Metric("Atomic number","${e.n}");Metric("Mass number","${m.roundToInt()}");Metric("Neutron count","$neutrons");Text("Stability varies by nuclide. This builder does not label an isotope stable without evaluated nuclear data.",fontSize=10.sp,lineHeight=15.sp,color=Gold)}}}}
@Composable private fun Ion(e:Element,back:()->Unit){var q by remember{mutableFloatStateOf(0f)};val maximumPositive=min(3,e.n);val charge=q.roundToInt().coerceIn(-3,maximumPositive);val electrons=e.n-charge;Column(Modifier.fillMaxSize()){Header("${e.name} (${e.symbol})","ION BUILDER • ADD OR REMOVE ELECTRONS",back);Row(Modifier.fillMaxSize().padding(18.dp),horizontalArrangement=Arrangement.spacedBy(16.dp)){Glass(Modifier.width(210.dp).fillMaxHeight()){Text("ION CONTROLS",fontSize=12.sp,color=Cyan);Text(if(charge==0)e.symbol else "${e.symbol}${if(charge>0)"${charge}+" else "${-charge}−"}",fontSize=48.sp,color=Cyan);Metric("Charge","$charge",Gold);Metric("Protons","${e.n}",Red);Metric("Electrons","$electrons",Cyan);Text("Electron change",fontSize=10.sp);Slider(value=charge.toFloat(),onValueChange={q=it.roundToInt().coerceIn(-3,maximumPositive).toFloat()},valueRange=-3f..maximumPositive.toFloat(),steps=(maximumPositive+2).coerceAtLeast(0))};Glass(Modifier.weight(1f).fillMaxHeight()){Atom(electrons);Text(if(charge>0)"${e.symbol} → ${e.symbol}${charge}+ + ${charge}e⁻" else if(charge<0)"${e.symbol} + ${-charge}e⁻ → ${e.symbol}${-charge}−" else "Neutral atom: protons = electrons",fontSize=13.sp,color=Gold)};Glass(Modifier.width(210.dp).fillMaxHeight()){Text("CHARGE ACCOUNTING",fontSize=12.sp,color=Cyan);Metric("Nuclear charge","+${e.n}");Metric("Electron charge","−$electrons");Metric("Net charge","$charge",Gold);Text("Changing ion charge changes electrons only. The nucleus and element identity remain unchanged.",fontSize=10.sp,lineHeight=16.sp)}}}}
@Composable private fun Molecule(){Canvas(Modifier.fillMaxSize()){val c=center;val l=Offset(c.x-size.width*.17f,c.y+size.height*.18f);val r=Offset(c.x+size.width*.17f,c.y+size.height*.18f);drawLine(Color.LightGray,c,l,18f);drawLine(Color.LightGray,c,r,18f);drawCircle(Brush.radialGradient(listOf(Color.White,Red,Color(0xFF7C102B)),c,size.minDimension*.12f),size.minDimension*.11f,c);drawCircle(Brush.radialGradient(listOf(Color.White,Color(0xFF9EB4C8)),l,size.minDimension*.07f),size.minDimension*.067f,l);drawCircle(Brush.radialGradient(listOf(Color.White,Color(0xFF9EB4C8)),r,size.minDimension*.07f),size.minDimension*.067f,r);drawArc(Gold,-58f,116f,false,topLeft=Offset(c.x-size.width*.11f,c.y),size=androidx.compose.ui.geometry.Size(size.width*.22f,size.height*.27f),style=Stroke(3f))}}
@Composable private fun Bond(back:()->Unit){Column(Modifier.fillMaxSize()){Header("Bond Builder","BUILD MOLECULES AND EXPLORE BONDING",back);Row(Modifier.fillMaxSize().padding(18.dp),horizontalArrangement=Arrangement.spacedBy(16.dp)){Glass(Modifier.width(190.dp).fillMaxHeight()){Text("ELEMENT PALETTE",fontSize=12.sp,color=Cyan);listOf("O  Oxygen","H  Hydrogen","C  Carbon","N  Nitrogen","S  Sulfur","Cl Chlorine").forEach{Text(it,Modifier.fillMaxWidth().background(if(it.startsWith("O"))Cyan.copy(.15f) else Color.Transparent).padding(8.dp),fontSize=11.sp)};OutlinedButton({}){Text("+ Add atom")}};Glass(Modifier.weight(1f).fillMaxHeight()){Box(Modifier.weight(1f).fillMaxWidth()){Molecule();Text("104.5°",Modifier.align(Alignment.Center).padding(top=90.dp),fontSize=11.sp,color=Gold)};Text("LEWIS STRUCTURE & POLARITY",fontSize=10.sp,color=Cyan);Text("H — O — H     •     molecular dipole",fontSize=14.sp)};Glass(Modifier.width(210.dp).fillMaxHeight()){Text("MOLECULE DATA",fontSize=12.sp,color=Cyan);Metric("Formula","H₂O");Metric("Bond type","polar covalent");Metric("Molecular geometry","bent");Metric("Electron geometry","tetrahedral");Metric("Bond angle","104.5°");Metric("Polarity","polar");Text("VSEPR: two bonding pairs and two lone pairs surround oxygen.",fontSize=10.sp,lineHeight=16.sp,color=Gold)}}}}
@Composable private fun States(back:()->Unit){var temp by remember{mutableFloatStateOf(25f)};val phase=if(temp<0)"SOLID" else if(temp<100)"LIQUID" else "GAS";val tint=if(phase=="SOLID")Blue else if(phase=="LIQUID")Cyan else Gold;Column(Modifier.fillMaxSize()){Header("States of Matter Lab","WATER (H₂O) AT 1 ATM • PHASE AND PARTICLE MOTION",back);Row(Modifier.fillMaxSize().padding(18.dp),horizontalArrangement=Arrangement.spacedBy(16.dp)){Glass(Modifier.width(200.dp).fillMaxHeight()){Text("TEMPERATURE",fontSize=11.sp,color=Cyan);Text("${temp.roundToInt()} °C",fontSize=34.sp,color=tint);Slider(value=temp,onValueChange={temp=it},valueRange=-50f..150f);Metric("Pressure","1.00 atm");Metric("State",phase,tint);Metric("Melting point","0 °C");Metric("Boiling point","100 °C");Text("Phase boundaries shown are for pure water at standard atmospheric pressure.",fontSize=9.sp,lineHeight=14.sp,color=Color.White.copy(.65f))};Glass(Modifier.weight(1f).fillMaxHeight()){Text(phase,fontSize=38.sp,color=tint);Particles(phase);Text(when(phase){"SOLID"->"Ordered lattice • molecules vibrate in place";"LIQUID"->"Close-packed molecules • flowing short-range order";else->"Widely separated molecules • rapid random motion"},fontSize=11.sp,color=Gold)};Glass(Modifier.width(200.dp).fillMaxHeight()){Text("MOLECULAR VIEW",fontSize=11.sp,color=Cyan);Metric("Substance","H₂O");Metric("Molar mass","18.01528 g/mol");Metric("Bond angle","104.5°");Metric("Geometry","bent");Metric("Polarity","polar");Text("Temperature changes average molecular kinetic energy. The molecules remain H₂O during a phase change.",fontSize=10.sp,lineHeight=16.sp)}}}}
@Composable private fun Particles(phase:String){val t by rememberInfiniteTransition(label="matter").animateFloat(0f,1f,infiniteRepeatable(tween(if(phase=="GAS")650 else 1600,easing=LinearEasing),RepeatMode.Restart),label="motion");Canvas(Modifier.fillMaxWidth().weight(1f)){drawRoundRect(Color(0x6625A8D0),style=Stroke(3f),cornerRadius=androidx.compose.ui.geometry.CornerRadius(18f));repeat(30){i->val base=when(phase){"SOLID"->Offset(size.width*(.16f+(i%6)*.135f),size.height*(.18f+(i/6)*.15f));"LIQUID"->Offset(size.width*(.10f+((i*37)%83)/100f),size.height*(.42f+((i*53)%48)/100f));else->Offset(size.width*(.06f+((i*37)%89)/100f),size.height*(.08f+((i*61)%84)/100f))};val motion=when(phase){"SOLID"->3f;"LIQUID"->10f;else->24f};val p=Offset(base.x+sin(i*1.7f+t*6.28f)*motion,base.y+cos(i*2.1f+t*5.4f)*motion);val angle=i*.7f;val h1=Offset(p.x+cos(angle)*9f,p.y+sin(angle)*9f);val h2=Offset(p.x+cos(angle+1.83f)*9f,p.y+sin(angle+1.83f)*9f);drawLine(Color.White.copy(.65f),p,h1,3f);drawLine(Color.White.copy(.65f),p,h2,3f);drawCircle(Red,6f,p);drawCircle(Color(0xFFE7F5FF),3.8f,h1);drawCircle(Color(0xFFE7F5FF),3.8f,h2)}}}
@Composable private fun Compare(a:Element,b:Element,set:(Element)->Unit,back:()->Unit){Column(Modifier.fillMaxSize()){Header("Compare Elements","SIDE-BY-SIDE SCIENTIFIC PROPERTIES",back);Row(Modifier.weight(1f).padding(20.dp),horizontalArrangement=Arrangement.spacedBy(16.dp)){listOf(a,b).forEach{e->val p=ELEMENT_PROPERTIES[e.n-1];Glass(Modifier.weight(1f).fillMaxHeight()){Text(e.symbol,fontSize=62.sp,fontWeight=FontWeight.Black,color=Color.White);Text(e.name,fontSize=24.sp,color=Color.White);Text("Atomic number ${e.n}\nAtomic weight ${p.atomicMass} u\nConfiguration ${p.configuration}\nElectronegativity ${p.electronegativity}\nDensity ${p.density} g/cm³\nMelting ${p.meltingPoint} K\nBoiling ${p.boilingPoint} K",lineHeight=22.sp,color=Color.White)}}};Row(Modifier.fillMaxWidth().padding(12.dp),horizontalArrangement=Arrangement.Center){all().filter{it.n in listOf(6,8,26,29,47,79)}.forEach{OutlinedButton({set(it)}){Text(it.symbol,color=Color.White)}}}}}
