package com.richardtalcott.periodic

/**
 * Generated from the NIH PubChem Periodic Table PUG REST dataset.
 * Source: https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON
 * Empty strings mean PubChem does not provide an established value.
 */
internal data class ElementProperties(
    val atomicNumber: Int,
    val symbol: String,
    val name: String,
    val atomicMass: String,
    val cpkHexColor: String,
    val electronConfiguration: String,
    val electronegativity: String,
    val atomicRadiusPm: String,
    val ionizationEnergyEv: String,
    val electronAffinityEv: String,
    val oxidationStates: String,
    val standardState: String,
    val meltingPointK: String,
    val boilingPointK: String,
    val densityGPerCm3: String,
    val category: String,
    val yearDiscovered: String,
    val representativeMassNumber: Int,
)

internal val ELEMENTS: List<ElementProperties> = listOf(
    ElementProperties(
        atomicNumber = 1, symbol = "H", name = "Hydrogen",
        atomicMass = "1.0080", cpkHexColor = "FFFFFF",
        electronConfiguration = "1s1", electronegativity = "2.2",
        atomicRadiusPm = "120", ionizationEnergyEv = "13.598",
        electronAffinityEv = "0.754", oxidationStates = "+1, -1",
        standardState = "Gas", meltingPointK = "13.81",
        boilingPointK = "20.28", densityGPerCm3 = "0.00008988",
        category = "Nonmetal", yearDiscovered = "1766",
        representativeMassNumber = 1,
    ),
    ElementProperties(
        atomicNumber = 2, symbol = "He", name = "Helium",
        atomicMass = "4.00260", cpkHexColor = "D9FFFF",
        electronConfiguration = "1s2", electronegativity = "",
        atomicRadiusPm = "140", ionizationEnergyEv = "24.587",
        electronAffinityEv = "", oxidationStates = "0",
        standardState = "Gas", meltingPointK = "0.95",
        boilingPointK = "4.22", densityGPerCm3 = "0.0001785",
        category = "Noble gas", yearDiscovered = "1868",
        representativeMassNumber = 4,
    ),
    ElementProperties(
        atomicNumber = 3, symbol = "Li", name = "Lithium",
        atomicMass = "7.0", cpkHexColor = "CC80FF",
        electronConfiguration = "[He]2s1", electronegativity = "0.98",
        atomicRadiusPm = "182", ionizationEnergyEv = "5.392",
        electronAffinityEv = "0.618", oxidationStates = "+1",
        standardState = "Solid", meltingPointK = "453.65",
        boilingPointK = "1615", densityGPerCm3 = "0.534",
        category = "Alkali metal", yearDiscovered = "1817",
        representativeMassNumber = 7,
    ),
    ElementProperties(
        atomicNumber = 4, symbol = "Be", name = "Beryllium",
        atomicMass = "9.012183", cpkHexColor = "C2FF00",
        electronConfiguration = "[He]2s2", electronegativity = "1.57",
        atomicRadiusPm = "153", ionizationEnergyEv = "9.323",
        electronAffinityEv = "", oxidationStates = "+2",
        standardState = "Solid", meltingPointK = "1560",
        boilingPointK = "2744", densityGPerCm3 = "1.85",
        category = "Alkaline earth metal", yearDiscovered = "1798",
        representativeMassNumber = 9,
    ),
    ElementProperties(
        atomicNumber = 5, symbol = "B", name = "Boron",
        atomicMass = "10.81", cpkHexColor = "FFB5B5",
        electronConfiguration = "[He]2s2 2p1", electronegativity = "2.04",
        atomicRadiusPm = "192", ionizationEnergyEv = "8.298",
        electronAffinityEv = "0.277", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "2348",
        boilingPointK = "4273", densityGPerCm3 = "2.37",
        category = "Metalloid", yearDiscovered = "1808",
        representativeMassNumber = 11,
    ),
    ElementProperties(
        atomicNumber = 6, symbol = "C", name = "Carbon",
        atomicMass = "12.011", cpkHexColor = "909090",
        electronConfiguration = "[He]2s2 2p2", electronegativity = "2.55",
        atomicRadiusPm = "170", ionizationEnergyEv = "11.260",
        electronAffinityEv = "1.263", oxidationStates = "+4, +2, -4",
        standardState = "Solid", meltingPointK = "3823",
        boilingPointK = "4098", densityGPerCm3 = "2.2670",
        category = "Nonmetal", yearDiscovered = "Ancient",
        representativeMassNumber = 12,
    ),
    ElementProperties(
        atomicNumber = 7, symbol = "N", name = "Nitrogen",
        atomicMass = "14.007", cpkHexColor = "3050F8",
        electronConfiguration = "[He] 2s2 2p3", electronegativity = "3.04",
        atomicRadiusPm = "155", ionizationEnergyEv = "14.534",
        electronAffinityEv = "", oxidationStates = "+5, +4, +3, +2, +1, -1, -2, -3",
        standardState = "Gas", meltingPointK = "63.15",
        boilingPointK = "77.36", densityGPerCm3 = "0.0012506",
        category = "Nonmetal", yearDiscovered = "1772",
        representativeMassNumber = 14,
    ),
    ElementProperties(
        atomicNumber = 8, symbol = "O", name = "Oxygen",
        atomicMass = "15.999", cpkHexColor = "FF0D0D",
        electronConfiguration = "[He]2s2 2p4", electronegativity = "3.44",
        atomicRadiusPm = "152", ionizationEnergyEv = "13.618",
        electronAffinityEv = "1.461", oxidationStates = "-2",
        standardState = "Gas", meltingPointK = "54.36",
        boilingPointK = "90.2", densityGPerCm3 = "0.001429",
        category = "Nonmetal", yearDiscovered = "1774",
        representativeMassNumber = 16,
    ),
    ElementProperties(
        atomicNumber = 9, symbol = "F", name = "Fluorine",
        atomicMass = "18.99840316", cpkHexColor = "90E050",
        electronConfiguration = "[He]2s2 2p5", electronegativity = "3.98",
        atomicRadiusPm = "135", ionizationEnergyEv = "17.423",
        electronAffinityEv = "3.339", oxidationStates = "-1",
        standardState = "Gas", meltingPointK = "53.53",
        boilingPointK = "85.03", densityGPerCm3 = "0.001696",
        category = "Halogen", yearDiscovered = "1670",
        representativeMassNumber = 19,
    ),
    ElementProperties(
        atomicNumber = 10, symbol = "Ne", name = "Neon",
        atomicMass = "20.180", cpkHexColor = "B3E3F5",
        electronConfiguration = "[He]2s2 2p6", electronegativity = "",
        atomicRadiusPm = "154", ionizationEnergyEv = "21.565",
        electronAffinityEv = "", oxidationStates = "0",
        standardState = "Gas", meltingPointK = "24.56",
        boilingPointK = "27.07", densityGPerCm3 = "0.0008999",
        category = "Noble gas", yearDiscovered = "1898",
        representativeMassNumber = 20,
    ),
    ElementProperties(
        atomicNumber = 11, symbol = "Na", name = "Sodium",
        atomicMass = "22.9897693", cpkHexColor = "AB5CF2",
        electronConfiguration = "[Ne]3s1", electronegativity = "0.93",
        atomicRadiusPm = "227", ionizationEnergyEv = "5.139",
        electronAffinityEv = "0.548", oxidationStates = "+1",
        standardState = "Solid", meltingPointK = "370.95",
        boilingPointK = "1156", densityGPerCm3 = "0.97",
        category = "Alkali metal", yearDiscovered = "1807",
        representativeMassNumber = 23,
    ),
    ElementProperties(
        atomicNumber = 12, symbol = "Mg", name = "Magnesium",
        atomicMass = "24.305", cpkHexColor = "8AFF00",
        electronConfiguration = "[Ne]3s2", electronegativity = "1.31",
        atomicRadiusPm = "173", ionizationEnergyEv = "7.646",
        electronAffinityEv = "", oxidationStates = "+2",
        standardState = "Solid", meltingPointK = "923",
        boilingPointK = "1363", densityGPerCm3 = "1.74",
        category = "Alkaline earth metal", yearDiscovered = "1808",
        representativeMassNumber = 24,
    ),
    ElementProperties(
        atomicNumber = 13, symbol = "Al", name = "Aluminum",
        atomicMass = "26.981538", cpkHexColor = "BFA6A6",
        electronConfiguration = "[Ne]3s2 3p1", electronegativity = "1.61",
        atomicRadiusPm = "184", ionizationEnergyEv = "5.986",
        electronAffinityEv = "0.441", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "933.437",
        boilingPointK = "2792", densityGPerCm3 = "2.70",
        category = "Post-transition metal", yearDiscovered = "Ancient",
        representativeMassNumber = 27,
    ),
    ElementProperties(
        atomicNumber = 14, symbol = "Si", name = "Silicon",
        atomicMass = "28.085", cpkHexColor = "F0C8A0",
        electronConfiguration = "[Ne]3s2 3p2", electronegativity = "1.9",
        atomicRadiusPm = "210", ionizationEnergyEv = "8.152",
        electronAffinityEv = "1.385", oxidationStates = "+4, +2, -4",
        standardState = "Solid", meltingPointK = "1687",
        boilingPointK = "3538", densityGPerCm3 = "2.3296",
        category = "Metalloid", yearDiscovered = "1854",
        representativeMassNumber = 28,
    ),
    ElementProperties(
        atomicNumber = 15, symbol = "P", name = "Phosphorus",
        atomicMass = "30.97376200", cpkHexColor = "FF8000",
        electronConfiguration = "[Ne]3s2 3p3", electronegativity = "2.19",
        atomicRadiusPm = "180", ionizationEnergyEv = "10.487",
        electronAffinityEv = "0.746", oxidationStates = "+5, +3, -3",
        standardState = "Solid", meltingPointK = "317.3",
        boilingPointK = "553.65", densityGPerCm3 = "1.82",
        category = "Nonmetal", yearDiscovered = "1669",
        representativeMassNumber = 31,
    ),
    ElementProperties(
        atomicNumber = 16, symbol = "S", name = "Sulfur",
        atomicMass = "32.07", cpkHexColor = "FFFF30",
        electronConfiguration = "[Ne]3s2 3p4", electronegativity = "2.58",
        atomicRadiusPm = "180", ionizationEnergyEv = "10.360",
        electronAffinityEv = "2.077", oxidationStates = "+6, +4, -2",
        standardState = "Solid", meltingPointK = "388.36",
        boilingPointK = "717.75", densityGPerCm3 = "2.067",
        category = "Nonmetal", yearDiscovered = "Ancient",
        representativeMassNumber = 32,
    ),
    ElementProperties(
        atomicNumber = 17, symbol = "Cl", name = "Chlorine",
        atomicMass = "35.45", cpkHexColor = "1FF01F",
        electronConfiguration = "[Ne]3s2 3p5", electronegativity = "3.16",
        atomicRadiusPm = "175", ionizationEnergyEv = "12.968",
        electronAffinityEv = "3.617", oxidationStates = "+7, +5, +1, -1",
        standardState = "Gas", meltingPointK = "171.65",
        boilingPointK = "239.11", densityGPerCm3 = "0.003214",
        category = "Halogen", yearDiscovered = "1774",
        representativeMassNumber = 35,
    ),
    ElementProperties(
        atomicNumber = 18, symbol = "Ar", name = "Argon",
        atomicMass = "39.9", cpkHexColor = "80D1E3",
        electronConfiguration = "[Ne]3s2 3p6", electronegativity = "",
        atomicRadiusPm = "188", ionizationEnergyEv = "15.760",
        electronAffinityEv = "", oxidationStates = "0",
        standardState = "Gas", meltingPointK = "83.8",
        boilingPointK = "87.3", densityGPerCm3 = "0.0017837",
        category = "Noble gas", yearDiscovered = "1894",
        representativeMassNumber = 40,
    ),
    ElementProperties(
        atomicNumber = 19, symbol = "K", name = "Potassium",
        atomicMass = "39.0983", cpkHexColor = "8F40D4",
        electronConfiguration = "[Ar]4s1", electronegativity = "0.82",
        atomicRadiusPm = "275", ionizationEnergyEv = "4.341",
        electronAffinityEv = "0.501", oxidationStates = "+1",
        standardState = "Solid", meltingPointK = "336.53",
        boilingPointK = "1032", densityGPerCm3 = "0.89",
        category = "Alkali metal", yearDiscovered = "1807",
        representativeMassNumber = 39,
    ),
    ElementProperties(
        atomicNumber = 20, symbol = "Ca", name = "Calcium",
        atomicMass = "40.08", cpkHexColor = "3DFF00",
        electronConfiguration = "[Ar]4s2", electronegativity = "1",
        atomicRadiusPm = "231", ionizationEnergyEv = "6.113",
        electronAffinityEv = "", oxidationStates = "+2",
        standardState = "Solid", meltingPointK = "1115",
        boilingPointK = "1757", densityGPerCm3 = "1.54",
        category = "Alkaline earth metal", yearDiscovered = "Ancient",
        representativeMassNumber = 40,
    ),
    ElementProperties(
        atomicNumber = 21, symbol = "Sc", name = "Scandium",
        atomicMass = "44.95591", cpkHexColor = "E6E6E6",
        electronConfiguration = "[Ar]4s2 3d1", electronegativity = "1.36",
        atomicRadiusPm = "211", ionizationEnergyEv = "6.561",
        electronAffinityEv = "0.188", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1814",
        boilingPointK = "3109", densityGPerCm3 = "2.99",
        category = "Transition metal", yearDiscovered = "1879",
        representativeMassNumber = 45,
    ),
    ElementProperties(
        atomicNumber = 22, symbol = "Ti", name = "Titanium",
        atomicMass = "47.867", cpkHexColor = "BFC2C7",
        electronConfiguration = "[Ar]4s2 3d2", electronegativity = "1.54",
        atomicRadiusPm = "187", ionizationEnergyEv = "6.828",
        electronAffinityEv = "0.079", oxidationStates = "+4, +3, +2",
        standardState = "Solid", meltingPointK = "1941",
        boilingPointK = "3560", densityGPerCm3 = "4.5",
        category = "Transition metal", yearDiscovered = "1791",
        representativeMassNumber = 48,
    ),
    ElementProperties(
        atomicNumber = 23, symbol = "V", name = "Vanadium",
        atomicMass = "50.9415", cpkHexColor = "A6A6AB",
        electronConfiguration = "[Ar]4s2 3d3", electronegativity = "1.63",
        atomicRadiusPm = "179", ionizationEnergyEv = "6.746",
        electronAffinityEv = "0.525", oxidationStates = "+5, +4, +3, +2",
        standardState = "Solid", meltingPointK = "2183",
        boilingPointK = "3680", densityGPerCm3 = "6.0",
        category = "Transition metal", yearDiscovered = "1801",
        representativeMassNumber = 51,
    ),
    ElementProperties(
        atomicNumber = 24, symbol = "Cr", name = "Chromium",
        atomicMass = "51.996", cpkHexColor = "8A99C7",
        electronConfiguration = "[Ar]3d5 4s1", electronegativity = "1.66",
        atomicRadiusPm = "189", ionizationEnergyEv = "6.767",
        electronAffinityEv = "0.666", oxidationStates = "+6, +3, +2",
        standardState = "Solid", meltingPointK = "2180",
        boilingPointK = "2944", densityGPerCm3 = "7.15",
        category = "Transition metal", yearDiscovered = "1797",
        representativeMassNumber = 52,
    ),
    ElementProperties(
        atomicNumber = 25, symbol = "Mn", name = "Manganese",
        atomicMass = "54.93804", cpkHexColor = "9C7AC7",
        electronConfiguration = "[Ar]4s2 3d5", electronegativity = "1.55",
        atomicRadiusPm = "197", ionizationEnergyEv = "7.434",
        electronAffinityEv = "", oxidationStates = "+7, +4, +3, +2",
        standardState = "Solid", meltingPointK = "1519",
        boilingPointK = "2334", densityGPerCm3 = "7.3",
        category = "Transition metal", yearDiscovered = "1774",
        representativeMassNumber = 55,
    ),
    ElementProperties(
        atomicNumber = 26, symbol = "Fe", name = "Iron",
        atomicMass = "55.84", cpkHexColor = "E06633",
        electronConfiguration = "[Ar]4s2 3d6", electronegativity = "1.83",
        atomicRadiusPm = "194", ionizationEnergyEv = "7.902",
        electronAffinityEv = "0.163", oxidationStates = "+3, +2",
        standardState = "Solid", meltingPointK = "1811",
        boilingPointK = "3134", densityGPerCm3 = "7.874",
        category = "Transition metal", yearDiscovered = "Ancient",
        representativeMassNumber = 56,
    ),
    ElementProperties(
        atomicNumber = 27, symbol = "Co", name = "Cobalt",
        atomicMass = "58.93319", cpkHexColor = "F090A0",
        electronConfiguration = "[Ar]4s2 3d7", electronegativity = "1.88",
        atomicRadiusPm = "192", ionizationEnergyEv = "7.881",
        electronAffinityEv = "0.661", oxidationStates = "+3, +2",
        standardState = "Solid", meltingPointK = "1768",
        boilingPointK = "3200", densityGPerCm3 = "8.86",
        category = "Transition metal", yearDiscovered = "1735",
        representativeMassNumber = 59,
    ),
    ElementProperties(
        atomicNumber = 28, symbol = "Ni", name = "Nickel",
        atomicMass = "58.693", cpkHexColor = "50D050",
        electronConfiguration = "[Ar]4s2 3d8", electronegativity = "1.91",
        atomicRadiusPm = "163", ionizationEnergyEv = "7.640",
        electronAffinityEv = "1.156", oxidationStates = "+3, +2",
        standardState = "Solid", meltingPointK = "1728",
        boilingPointK = "3186", densityGPerCm3 = "8.912",
        category = "Transition metal", yearDiscovered = "1751",
        representativeMassNumber = 59,
    ),
    ElementProperties(
        atomicNumber = 29, symbol = "Cu", name = "Copper",
        atomicMass = "63.55", cpkHexColor = "C88033",
        electronConfiguration = "[Ar]4s1 3d10", electronegativity = "1.9",
        atomicRadiusPm = "140", ionizationEnergyEv = "7.726",
        electronAffinityEv = "1.228", oxidationStates = "+2, +1",
        standardState = "Solid", meltingPointK = "1357.77",
        boilingPointK = "2835", densityGPerCm3 = "8.933",
        category = "Transition metal", yearDiscovered = "Ancient",
        representativeMassNumber = 64,
    ),
    ElementProperties(
        atomicNumber = 30, symbol = "Zn", name = "Zinc",
        atomicMass = "65.4", cpkHexColor = "7D80B0",
        electronConfiguration = "[Ar]4s2 3d10", electronegativity = "1.65",
        atomicRadiusPm = "139", ionizationEnergyEv = "9.394",
        electronAffinityEv = "", oxidationStates = "+2",
        standardState = "Solid", meltingPointK = "692.68",
        boilingPointK = "1180", densityGPerCm3 = "7.134",
        category = "Transition metal", yearDiscovered = "1746",
        representativeMassNumber = 65,
    ),
    ElementProperties(
        atomicNumber = 31, symbol = "Ga", name = "Gallium",
        atomicMass = "69.723", cpkHexColor = "C28F8F",
        electronConfiguration = "[Ar]4s2 3d10 4p1", electronegativity = "1.81",
        atomicRadiusPm = "187", ionizationEnergyEv = "5.999",
        electronAffinityEv = "0.3", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "302.91",
        boilingPointK = "2477", densityGPerCm3 = "5.91",
        category = "Post-transition metal", yearDiscovered = "1875",
        representativeMassNumber = 70,
    ),
    ElementProperties(
        atomicNumber = 32, symbol = "Ge", name = "Germanium",
        atomicMass = "72.63", cpkHexColor = "668F8F",
        electronConfiguration = "[Ar]4s2 3d10 4p2", electronegativity = "2.01",
        atomicRadiusPm = "211", ionizationEnergyEv = "7.900",
        electronAffinityEv = "1.35", oxidationStates = "+4, +2",
        standardState = "Solid", meltingPointK = "1211.4",
        boilingPointK = "3106", densityGPerCm3 = "5.323",
        category = "Metalloid", yearDiscovered = "1886",
        representativeMassNumber = 73,
    ),
    ElementProperties(
        atomicNumber = 33, symbol = "As", name = "Arsenic",
        atomicMass = "74.92159", cpkHexColor = "BD80E3",
        electronConfiguration = "[Ar]4s2 3d10 4p3", electronegativity = "2.18",
        atomicRadiusPm = "185", ionizationEnergyEv = "9.815",
        electronAffinityEv = "0.81", oxidationStates = "+5, +3, -3",
        standardState = "Solid", meltingPointK = "1090",
        boilingPointK = "887", densityGPerCm3 = "5.776",
        category = "Metalloid", yearDiscovered = "Ancient",
        representativeMassNumber = 75,
    ),
    ElementProperties(
        atomicNumber = 34, symbol = "Se", name = "Selenium",
        atomicMass = "78.97", cpkHexColor = "FFA100",
        electronConfiguration = "[Ar]4s2 3d10 4p4", electronegativity = "2.55",
        atomicRadiusPm = "190", ionizationEnergyEv = "9.752",
        electronAffinityEv = "2.021", oxidationStates = "+6, +4, -2",
        standardState = "Solid", meltingPointK = "493.65",
        boilingPointK = "958", densityGPerCm3 = "4.809",
        category = "Nonmetal", yearDiscovered = "1817",
        representativeMassNumber = 79,
    ),
    ElementProperties(
        atomicNumber = 35, symbol = "Br", name = "Bromine",
        atomicMass = "79.90", cpkHexColor = "A62929",
        electronConfiguration = "[Ar]4s2 3d10 4p5", electronegativity = "2.96",
        atomicRadiusPm = "183", ionizationEnergyEv = "11.814",
        electronAffinityEv = "3.365", oxidationStates = "+5, +1, -1",
        standardState = "Liquid", meltingPointK = "265.95",
        boilingPointK = "331.95", densityGPerCm3 = "3.11",
        category = "Halogen", yearDiscovered = "1826",
        representativeMassNumber = 80,
    ),
    ElementProperties(
        atomicNumber = 36, symbol = "Kr", name = "Krypton",
        atomicMass = "83.80", cpkHexColor = "5CB8D1",
        electronConfiguration = "[Ar]4s2 3d10 4p6", electronegativity = "3",
        atomicRadiusPm = "202", ionizationEnergyEv = "14.000",
        electronAffinityEv = "", oxidationStates = "0",
        standardState = "Gas", meltingPointK = "115.79",
        boilingPointK = "119.93", densityGPerCm3 = "0.003733",
        category = "Noble gas", yearDiscovered = "1898",
        representativeMassNumber = 84,
    ),
    ElementProperties(
        atomicNumber = 37, symbol = "Rb", name = "Rubidium",
        atomicMass = "85.468", cpkHexColor = "702EB0",
        electronConfiguration = "[Kr]5s1", electronegativity = "0.82",
        atomicRadiusPm = "303", ionizationEnergyEv = "4.177",
        electronAffinityEv = "0.468", oxidationStates = "+1",
        standardState = "Solid", meltingPointK = "312.46",
        boilingPointK = "961", densityGPerCm3 = "1.53",
        category = "Alkali metal", yearDiscovered = "1861",
        representativeMassNumber = 85,
    ),
    ElementProperties(
        atomicNumber = 38, symbol = "Sr", name = "Strontium",
        atomicMass = "87.62", cpkHexColor = "00FF00",
        electronConfiguration = "[Kr]5s2", electronegativity = "0.95",
        atomicRadiusPm = "249", ionizationEnergyEv = "5.695",
        electronAffinityEv = "", oxidationStates = "+2",
        standardState = "Solid", meltingPointK = "1050",
        boilingPointK = "1655", densityGPerCm3 = "2.64",
        category = "Alkaline earth metal", yearDiscovered = "1790",
        representativeMassNumber = 88,
    ),
    ElementProperties(
        atomicNumber = 39, symbol = "Y", name = "Yttrium",
        atomicMass = "88.90584", cpkHexColor = "94FFFF",
        electronConfiguration = "[Kr]5s2 4d1", electronegativity = "1.22",
        atomicRadiusPm = "219", ionizationEnergyEv = "6.217",
        electronAffinityEv = "0.307", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1795",
        boilingPointK = "3618", densityGPerCm3 = "4.47",
        category = "Transition metal", yearDiscovered = "1794",
        representativeMassNumber = 89,
    ),
    ElementProperties(
        atomicNumber = 40, symbol = "Zr", name = "Zirconium",
        atomicMass = "91.22", cpkHexColor = "94E0E0",
        electronConfiguration = "[Kr]5s2 4d2", electronegativity = "1.33",
        atomicRadiusPm = "186", ionizationEnergyEv = "6.634",
        electronAffinityEv = "0.426", oxidationStates = "+4",
        standardState = "Solid", meltingPointK = "2128",
        boilingPointK = "4682", densityGPerCm3 = "6.52",
        category = "Transition metal", yearDiscovered = "1789",
        representativeMassNumber = 91,
    ),
    ElementProperties(
        atomicNumber = 41, symbol = "Nb", name = "Niobium",
        atomicMass = "92.90637", cpkHexColor = "73C2C9",
        electronConfiguration = "[Kr]5s1 4d4", electronegativity = "1.6",
        atomicRadiusPm = "207", ionizationEnergyEv = "6.759",
        electronAffinityEv = "0.893", oxidationStates = "+5, +3",
        standardState = "Solid", meltingPointK = "2750",
        boilingPointK = "5017", densityGPerCm3 = "8.57",
        category = "Transition metal", yearDiscovered = "1801",
        representativeMassNumber = 93,
    ),
    ElementProperties(
        atomicNumber = 42, symbol = "Mo", name = "Molybdenum",
        atomicMass = "95.95", cpkHexColor = "54B5B5",
        electronConfiguration = "[Kr]5s1 4d5", electronegativity = "2.16",
        atomicRadiusPm = "209", ionizationEnergyEv = "7.092",
        electronAffinityEv = "0.746", oxidationStates = "+6",
        standardState = "Solid", meltingPointK = "2896",
        boilingPointK = "4912", densityGPerCm3 = "10.2",
        category = "Transition metal", yearDiscovered = "1778",
        representativeMassNumber = 96,
    ),
    ElementProperties(
        atomicNumber = 43, symbol = "Tc", name = "Technetium",
        atomicMass = "96.90636", cpkHexColor = "3B9E9E",
        electronConfiguration = "[Kr]5s2 4d5", electronegativity = "1.9",
        atomicRadiusPm = "209", ionizationEnergyEv = "7.28",
        electronAffinityEv = "0.55", oxidationStates = "+7, +6, +4",
        standardState = "Solid", meltingPointK = "2430",
        boilingPointK = "4538", densityGPerCm3 = "11",
        category = "Transition metal", yearDiscovered = "1937",
        representativeMassNumber = 97,
    ),
    ElementProperties(
        atomicNumber = 44, symbol = "Ru", name = "Ruthenium",
        atomicMass = "101.1", cpkHexColor = "248F8F",
        electronConfiguration = "[Kr]5s1 4d7", electronegativity = "2.2",
        atomicRadiusPm = "207", ionizationEnergyEv = "7.361",
        electronAffinityEv = "1.05", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "2607",
        boilingPointK = "4423", densityGPerCm3 = "12.1",
        category = "Transition metal", yearDiscovered = "1827",
        representativeMassNumber = 101,
    ),
    ElementProperties(
        atomicNumber = 45, symbol = "Rh", name = "Rhodium",
        atomicMass = "102.9055", cpkHexColor = "0A7D8C",
        electronConfiguration = "[Kr]5s1 4d8", electronegativity = "2.28",
        atomicRadiusPm = "195", ionizationEnergyEv = "7.459",
        electronAffinityEv = "1.137", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "2237",
        boilingPointK = "3968", densityGPerCm3 = "12.4",
        category = "Transition metal", yearDiscovered = "1803",
        representativeMassNumber = 103,
    ),
    ElementProperties(
        atomicNumber = 46, symbol = "Pd", name = "Palladium",
        atomicMass = "106.42", cpkHexColor = "6985",
        electronConfiguration = "[Kr]4d10", electronegativity = "2.2",
        atomicRadiusPm = "202", ionizationEnergyEv = "8.337",
        electronAffinityEv = "0.557", oxidationStates = "+3, +2",
        standardState = "Solid", meltingPointK = "1828.05",
        boilingPointK = "3236", densityGPerCm3 = "12.0",
        category = "Transition metal", yearDiscovered = "1803",
        representativeMassNumber = 106,
    ),
    ElementProperties(
        atomicNumber = 47, symbol = "Ag", name = "Silver",
        atomicMass = "107.868", cpkHexColor = "C0C0C0",
        electronConfiguration = "[Kr]5s1 4d10", electronegativity = "1.93",
        atomicRadiusPm = "172", ionizationEnergyEv = "7.576",
        electronAffinityEv = "1.302", oxidationStates = "+1",
        standardState = "Solid", meltingPointK = "1234.93",
        boilingPointK = "2435", densityGPerCm3 = "10.501",
        category = "Transition metal", yearDiscovered = "Ancient",
        representativeMassNumber = 108,
    ),
    ElementProperties(
        atomicNumber = 48, symbol = "Cd", name = "Cadmium",
        atomicMass = "112.41", cpkHexColor = "FFD98F",
        electronConfiguration = "[Kr]5s2 4d10", electronegativity = "1.69",
        atomicRadiusPm = "158", ionizationEnergyEv = "8.994",
        electronAffinityEv = "", oxidationStates = "+2",
        standardState = "Solid", meltingPointK = "594.22",
        boilingPointK = "1040", densityGPerCm3 = "8.69",
        category = "Transition metal", yearDiscovered = "1817",
        representativeMassNumber = 112,
    ),
    ElementProperties(
        atomicNumber = 49, symbol = "In", name = "Indium",
        atomicMass = "114.818", cpkHexColor = "A67573",
        electronConfiguration = "[Kr]5s2 4d10 5p1", electronegativity = "1.78",
        atomicRadiusPm = "193", ionizationEnergyEv = "5.786",
        electronAffinityEv = "0.3", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "429.75",
        boilingPointK = "2345", densityGPerCm3 = "7.31",
        category = "Post-transition metal", yearDiscovered = "1863",
        representativeMassNumber = 115,
    ),
    ElementProperties(
        atomicNumber = 50, symbol = "Sn", name = "Tin",
        atomicMass = "118.71", cpkHexColor = "668080",
        electronConfiguration = "[Kr]5s2 4d10 5p2", electronegativity = "1.96",
        atomicRadiusPm = "217", ionizationEnergyEv = "7.344",
        electronAffinityEv = "1.2", oxidationStates = "+4, +2",
        standardState = "Solid", meltingPointK = "505.08",
        boilingPointK = "2875", densityGPerCm3 = "7.287",
        category = "Post-transition metal", yearDiscovered = "Ancient",
        representativeMassNumber = 119,
    ),
    ElementProperties(
        atomicNumber = 51, symbol = "Sb", name = "Antimony",
        atomicMass = "121.760", cpkHexColor = "9E63B5",
        electronConfiguration = "[Kr]5s2 4d10 5p3", electronegativity = "2.05",
        atomicRadiusPm = "206", ionizationEnergyEv = "8.64",
        electronAffinityEv = "1.07", oxidationStates = "+5, +3, -3",
        standardState = "Solid", meltingPointK = "903.78",
        boilingPointK = "1860", densityGPerCm3 = "6.685",
        category = "Metalloid", yearDiscovered = "Ancient",
        representativeMassNumber = 122,
    ),
    ElementProperties(
        atomicNumber = 52, symbol = "Te", name = "Tellurium",
        atomicMass = "127.6", cpkHexColor = "D47A00",
        electronConfiguration = "[Kr]5s2 4d10 5p4", electronegativity = "2.1",
        atomicRadiusPm = "206", ionizationEnergyEv = "9.010",
        electronAffinityEv = "1.971", oxidationStates = "+6, +4, -2",
        standardState = "Solid", meltingPointK = "722.66",
        boilingPointK = "1261", densityGPerCm3 = "6.232",
        category = "Metalloid", yearDiscovered = "1782",
        representativeMassNumber = 128,
    ),
    ElementProperties(
        atomicNumber = 53, symbol = "I", name = "Iodine",
        atomicMass = "126.9045", cpkHexColor = "940094",
        electronConfiguration = "[Kr]5s2 4d10 5p5", electronegativity = "2.66",
        atomicRadiusPm = "198", ionizationEnergyEv = "10.451",
        electronAffinityEv = "3.059", oxidationStates = "+7, +5, +1, -1",
        standardState = "Solid", meltingPointK = "386.85",
        boilingPointK = "457.55", densityGPerCm3 = "4.93",
        category = "Halogen", yearDiscovered = "1811",
        representativeMassNumber = 127,
    ),
    ElementProperties(
        atomicNumber = 54, symbol = "Xe", name = "Xenon",
        atomicMass = "131.29", cpkHexColor = "429EB0",
        electronConfiguration = "[Kr]5s2 4d10 5p6", electronegativity = "2.6",
        atomicRadiusPm = "216", ionizationEnergyEv = "12.130",
        electronAffinityEv = "", oxidationStates = "0",
        standardState = "Gas", meltingPointK = "161.36",
        boilingPointK = "165.03", densityGPerCm3 = "0.005887",
        category = "Noble gas", yearDiscovered = "1898",
        representativeMassNumber = 131,
    ),
    ElementProperties(
        atomicNumber = 55, symbol = "Cs", name = "Cesium",
        atomicMass = "132.9054520", cpkHexColor = "57178F",
        electronConfiguration = "[Xe]6s1", electronegativity = "0.79",
        atomicRadiusPm = "343", ionizationEnergyEv = "3.894",
        electronAffinityEv = "0.472", oxidationStates = "+1",
        standardState = "Solid", meltingPointK = "301.59",
        boilingPointK = "944", densityGPerCm3 = "1.93",
        category = "Alkali metal", yearDiscovered = "1860",
        representativeMassNumber = 133,
    ),
    ElementProperties(
        atomicNumber = 56, symbol = "Ba", name = "Barium",
        atomicMass = "137.33", cpkHexColor = "00C900",
        electronConfiguration = "[Xe]6s2", electronegativity = "0.89",
        atomicRadiusPm = "268", ionizationEnergyEv = "5.212",
        electronAffinityEv = "", oxidationStates = "+2",
        standardState = "Solid", meltingPointK = "1000",
        boilingPointK = "2170", densityGPerCm3 = "3.62",
        category = "Alkaline earth metal", yearDiscovered = "1808",
        representativeMassNumber = 137,
    ),
    ElementProperties(
        atomicNumber = 57, symbol = "La", name = "Lanthanum",
        atomicMass = "138.9055", cpkHexColor = "70D4FF",
        electronConfiguration = "[Xe]6s2 5d1", electronegativity = "1.1",
        atomicRadiusPm = "240", ionizationEnergyEv = "5.577",
        electronAffinityEv = "0.5", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1191",
        boilingPointK = "3737", densityGPerCm3 = "6.15",
        category = "Lanthanide", yearDiscovered = "1839",
        representativeMassNumber = 139,
    ),
    ElementProperties(
        atomicNumber = 58, symbol = "Ce", name = "Cerium",
        atomicMass = "140.116", cpkHexColor = "FFFFC7",
        electronConfiguration = "[Xe]6s2 4f1 5d1", electronegativity = "1.12",
        atomicRadiusPm = "235", ionizationEnergyEv = "5.539",
        electronAffinityEv = "0.5", oxidationStates = "+4, +3",
        standardState = "Solid", meltingPointK = "1071",
        boilingPointK = "3697", densityGPerCm3 = "6.770",
        category = "Lanthanide", yearDiscovered = "1803",
        representativeMassNumber = 140,
    ),
    ElementProperties(
        atomicNumber = 59, symbol = "Pr", name = "Praseodymium",
        atomicMass = "140.90766", cpkHexColor = "D9FFC7",
        electronConfiguration = "[Xe]6s2 4f3", electronegativity = "1.13",
        atomicRadiusPm = "239", ionizationEnergyEv = "5.464",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1204",
        boilingPointK = "3793", densityGPerCm3 = "6.77",
        category = "Lanthanide", yearDiscovered = "1885",
        representativeMassNumber = 141,
    ),
    ElementProperties(
        atomicNumber = 60, symbol = "Nd", name = "Neodymium",
        atomicMass = "144.24", cpkHexColor = "C7FFC7",
        electronConfiguration = "[Xe]6s2 4f4", electronegativity = "1.14",
        atomicRadiusPm = "229", ionizationEnergyEv = "5.525",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1294",
        boilingPointK = "3347", densityGPerCm3 = "7.01",
        category = "Lanthanide", yearDiscovered = "1885",
        representativeMassNumber = 144,
    ),
    ElementProperties(
        atomicNumber = 61, symbol = "Pm", name = "Promethium",
        atomicMass = "144.91276", cpkHexColor = "A3FFC7",
        electronConfiguration = "[Xe]6s2 4f5", electronegativity = "",
        atomicRadiusPm = "236", ionizationEnergyEv = "5.55",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1315",
        boilingPointK = "3273", densityGPerCm3 = "7.26",
        category = "Lanthanide", yearDiscovered = "1945",
        representativeMassNumber = 145,
    ),
    ElementProperties(
        atomicNumber = 62, symbol = "Sm", name = "Samarium",
        atomicMass = "150.4", cpkHexColor = "8FFFC7",
        electronConfiguration = "[Xe]6s2 4f6", electronegativity = "1.17",
        atomicRadiusPm = "229", ionizationEnergyEv = "5.644",
        electronAffinityEv = "", oxidationStates = "+3, +2",
        standardState = "Solid", meltingPointK = "1347",
        boilingPointK = "2067", densityGPerCm3 = "7.52",
        category = "Lanthanide", yearDiscovered = "1879",
        representativeMassNumber = 150,
    ),
    ElementProperties(
        atomicNumber = 63, symbol = "Eu", name = "Europium",
        atomicMass = "151.964", cpkHexColor = "61FFC7",
        electronConfiguration = "[Xe]6s2 4f7", electronegativity = "",
        atomicRadiusPm = "233", ionizationEnergyEv = "5.670",
        electronAffinityEv = "", oxidationStates = "+3, +2",
        standardState = "Solid", meltingPointK = "1095",
        boilingPointK = "1802", densityGPerCm3 = "5.24",
        category = "Lanthanide", yearDiscovered = "1901",
        representativeMassNumber = 152,
    ),
    ElementProperties(
        atomicNumber = 64, symbol = "Gd", name = "Gadolinium",
        atomicMass = "157.25", cpkHexColor = "45FFC7",
        electronConfiguration = "[Xe]6s2 4f7 5d1", electronegativity = "1.2",
        atomicRadiusPm = "237", ionizationEnergyEv = "6.150",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1586",
        boilingPointK = "3546", densityGPerCm3 = "7.90",
        category = "Lanthanide", yearDiscovered = "1880",
        representativeMassNumber = 157,
    ),
    ElementProperties(
        atomicNumber = 65, symbol = "Tb", name = "Terbium",
        atomicMass = "158.92535", cpkHexColor = "30FFC7",
        electronConfiguration = "[Xe]6s2 4f9", electronegativity = "",
        atomicRadiusPm = "221", ionizationEnergyEv = "5.864",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1629",
        boilingPointK = "3503", densityGPerCm3 = "8.23",
        category = "Lanthanide", yearDiscovered = "1843",
        representativeMassNumber = 159,
    ),
    ElementProperties(
        atomicNumber = 66, symbol = "Dy", name = "Dysprosium",
        atomicMass = "162.500", cpkHexColor = "1FFFC7",
        electronConfiguration = "[Xe]6s2 4f10", electronegativity = "1.22",
        atomicRadiusPm = "229", ionizationEnergyEv = "5.939",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1685",
        boilingPointK = "2840", densityGPerCm3 = "8.55",
        category = "Lanthanide", yearDiscovered = "1886",
        representativeMassNumber = 163,
    ),
    ElementProperties(
        atomicNumber = 67, symbol = "Ho", name = "Holmium",
        atomicMass = "164.93033", cpkHexColor = "00FF9C",
        electronConfiguration = "[Xe]6s2 4f11", electronegativity = "1.23",
        atomicRadiusPm = "216", ionizationEnergyEv = "6.022",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1747",
        boilingPointK = "2973", densityGPerCm3 = "8.80",
        category = "Lanthanide", yearDiscovered = "1878",
        representativeMassNumber = 165,
    ),
    ElementProperties(
        atomicNumber = 68, symbol = "Er", name = "Erbium",
        atomicMass = "167.26", cpkHexColor = "",
        electronConfiguration = "[Xe]6s2 4f12", electronegativity = "1.24",
        atomicRadiusPm = "235", ionizationEnergyEv = "6.108",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1802",
        boilingPointK = "3141", densityGPerCm3 = "9.07",
        category = "Lanthanide", yearDiscovered = "1843",
        representativeMassNumber = 167,
    ),
    ElementProperties(
        atomicNumber = 69, symbol = "Tm", name = "Thulium",
        atomicMass = "168.93422", cpkHexColor = "00D452",
        electronConfiguration = "[Xe]6s2 4f13", electronegativity = "1.25",
        atomicRadiusPm = "227", ionizationEnergyEv = "6.184",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1818",
        boilingPointK = "2223", densityGPerCm3 = "9.32",
        category = "Lanthanide", yearDiscovered = "1879",
        representativeMassNumber = 169,
    ),
    ElementProperties(
        atomicNumber = 70, symbol = "Yb", name = "Ytterbium",
        atomicMass = "173.05", cpkHexColor = "00BF38",
        electronConfiguration = "[Xe]6s2 4f14", electronegativity = "",
        atomicRadiusPm = "242", ionizationEnergyEv = "6.254",
        electronAffinityEv = "", oxidationStates = "+3, +2",
        standardState = "Solid", meltingPointK = "1092",
        boilingPointK = "1469", densityGPerCm3 = "6.90",
        category = "Lanthanide", yearDiscovered = "1878",
        representativeMassNumber = 173,
    ),
    ElementProperties(
        atomicNumber = 71, symbol = "Lu", name = "Lutetium",
        atomicMass = "174.9667", cpkHexColor = "00AB24",
        electronConfiguration = "[Xe]6s2 4f14 5d1", electronegativity = "1.27",
        atomicRadiusPm = "221", ionizationEnergyEv = "5.426",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1936",
        boilingPointK = "3675", densityGPerCm3 = "9.84",
        category = "Lanthanide", yearDiscovered = "1907",
        representativeMassNumber = 175,
    ),
    ElementProperties(
        atomicNumber = 72, symbol = "Hf", name = "Hafnium",
        atomicMass = "178.49", cpkHexColor = "4DC2FF",
        electronConfiguration = "[Xe]6s2 4f14 5d2", electronegativity = "1.3",
        atomicRadiusPm = "212", ionizationEnergyEv = "6.825",
        electronAffinityEv = "", oxidationStates = "+4",
        standardState = "Solid", meltingPointK = "2506",
        boilingPointK = "4876", densityGPerCm3 = "13.3",
        category = "Transition metal", yearDiscovered = "1923",
        representativeMassNumber = 178,
    ),
    ElementProperties(
        atomicNumber = 73, symbol = "Ta", name = "Tantalum",
        atomicMass = "180.9479", cpkHexColor = "4DA6FF",
        electronConfiguration = "[Xe]6s2 4f14 5d3", electronegativity = "1.5",
        atomicRadiusPm = "217", ionizationEnergyEv = "7.89",
        electronAffinityEv = "0.322", oxidationStates = "+5",
        standardState = "Solid", meltingPointK = "3290",
        boilingPointK = "5731", densityGPerCm3 = "16.4",
        category = "Transition metal", yearDiscovered = "1802",
        representativeMassNumber = 181,
    ),
    ElementProperties(
        atomicNumber = 74, symbol = "W", name = "Tungsten",
        atomicMass = "183.84", cpkHexColor = "2194D6",
        electronConfiguration = "[Xe]6s2 4f14 5d4", electronegativity = "2.36",
        atomicRadiusPm = "210", ionizationEnergyEv = "7.98",
        electronAffinityEv = "0.815", oxidationStates = "+6",
        standardState = "Solid", meltingPointK = "3695",
        boilingPointK = "5828", densityGPerCm3 = "19.3",
        category = "Transition metal", yearDiscovered = "1783",
        representativeMassNumber = 184,
    ),
    ElementProperties(
        atomicNumber = 75, symbol = "Re", name = "Rhenium",
        atomicMass = "186.207", cpkHexColor = "267DAB",
        electronConfiguration = "[Xe]6s2 4f14 5d5", electronegativity = "1.9",
        atomicRadiusPm = "217", ionizationEnergyEv = "7.88",
        electronAffinityEv = "0.15", oxidationStates = "+7, +6, +4",
        standardState = "Solid", meltingPointK = "3459",
        boilingPointK = "5869", densityGPerCm3 = "20.8",
        category = "Transition metal", yearDiscovered = "1925",
        representativeMassNumber = 186,
    ),
    ElementProperties(
        atomicNumber = 76, symbol = "Os", name = "Osmium",
        atomicMass = "190.2", cpkHexColor = "266696",
        electronConfiguration = "[Xe]6s2 4f14 5d6", electronegativity = "2.2",
        atomicRadiusPm = "216", ionizationEnergyEv = "8.7",
        electronAffinityEv = "1.1", oxidationStates = "+4, +3",
        standardState = "Solid", meltingPointK = "3306",
        boilingPointK = "5285", densityGPerCm3 = "22.57",
        category = "Transition metal", yearDiscovered = "1803",
        representativeMassNumber = 190,
    ),
    ElementProperties(
        atomicNumber = 77, symbol = "Ir", name = "Iridium",
        atomicMass = "192.22", cpkHexColor = "175487",
        electronConfiguration = "[Xe]6s2 4f14 5d7", electronegativity = "2.2",
        atomicRadiusPm = "202", ionizationEnergyEv = "9.1",
        electronAffinityEv = "1.565", oxidationStates = "+4, +3",
        standardState = "Solid", meltingPointK = "2719",
        boilingPointK = "4701", densityGPerCm3 = "22.42",
        category = "Transition metal", yearDiscovered = "1803",
        representativeMassNumber = 192,
    ),
    ElementProperties(
        atomicNumber = 78, symbol = "Pt", name = "Platinum",
        atomicMass = "195.08", cpkHexColor = "D0D0E0",
        electronConfiguration = "[Xe]6s1 4f14 5d9", electronegativity = "2.28",
        atomicRadiusPm = "209", ionizationEnergyEv = "9",
        electronAffinityEv = "2.128", oxidationStates = "+4, +2",
        standardState = "Solid", meltingPointK = "2041.55",
        boilingPointK = "4098", densityGPerCm3 = "21.46",
        category = "Transition metal", yearDiscovered = "1735",
        representativeMassNumber = 195,
    ),
    ElementProperties(
        atomicNumber = 79, symbol = "Au", name = "Gold",
        atomicMass = "196.96657", cpkHexColor = "FFD123",
        electronConfiguration = "[Xe]6s1 4f14 5d10", electronegativity = "2.54",
        atomicRadiusPm = "166", ionizationEnergyEv = "9.226",
        electronAffinityEv = "2.309", oxidationStates = "+3, +1",
        standardState = "Solid", meltingPointK = "1337.33",
        boilingPointK = "3129", densityGPerCm3 = "19.282",
        category = "Transition metal", yearDiscovered = "Ancient",
        representativeMassNumber = 197,
    ),
    ElementProperties(
        atomicNumber = 80, symbol = "Hg", name = "Mercury",
        atomicMass = "200.59", cpkHexColor = "B8B8D0",
        electronConfiguration = "[Xe]6s2 4f14 5d10", electronegativity = "2",
        atomicRadiusPm = "209", ionizationEnergyEv = "10.438",
        electronAffinityEv = "", oxidationStates = "+2, +1",
        standardState = "Liquid", meltingPointK = "234.32",
        boilingPointK = "629.88", densityGPerCm3 = "13.5336",
        category = "Transition metal", yearDiscovered = "Ancient",
        representativeMassNumber = 201,
    ),
    ElementProperties(
        atomicNumber = 81, symbol = "Tl", name = "Thallium",
        atomicMass = "204.383", cpkHexColor = "A6544D",
        electronConfiguration = "[Xe]6s2 4f14 5d10 6p1", electronegativity = "1.62",
        atomicRadiusPm = "196", ionizationEnergyEv = "6.108",
        electronAffinityEv = "0.2", oxidationStates = "+3, +1",
        standardState = "Solid", meltingPointK = "577",
        boilingPointK = "1746", densityGPerCm3 = "11.8",
        category = "Post-transition metal", yearDiscovered = "1861",
        representativeMassNumber = 204,
    ),
    ElementProperties(
        atomicNumber = 82, symbol = "Pb", name = "Lead",
        atomicMass = "207", cpkHexColor = "575961",
        electronConfiguration = "[Xe]6s2 4f14 5d10 6p2", electronegativity = "2.33",
        atomicRadiusPm = "202", ionizationEnergyEv = "7.417",
        electronAffinityEv = "0.36", oxidationStates = "+4, +2",
        standardState = "Solid", meltingPointK = "600.61",
        boilingPointK = "2022", densityGPerCm3 = "11.342",
        category = "Post-transition metal", yearDiscovered = "Ancient",
        representativeMassNumber = 207,
    ),
    ElementProperties(
        atomicNumber = 83, symbol = "Bi", name = "Bismuth",
        atomicMass = "208.98040", cpkHexColor = "9E4FB5",
        electronConfiguration = "[Xe]6s2 4f14 5d10 6p3", electronegativity = "2.02",
        atomicRadiusPm = "207", ionizationEnergyEv = "7.289",
        electronAffinityEv = "0.946", oxidationStates = "+5, +3",
        standardState = "Solid", meltingPointK = "544.55",
        boilingPointK = "1837", densityGPerCm3 = "9.807",
        category = "Post-transition metal", yearDiscovered = "1753",
        representativeMassNumber = 209,
    ),
    ElementProperties(
        atomicNumber = 84, symbol = "Po", name = "Polonium",
        atomicMass = "208.98243", cpkHexColor = "AB5C00",
        electronConfiguration = "[Xe]6s2 4f14 5d10 6p4", electronegativity = "2",
        atomicRadiusPm = "197", ionizationEnergyEv = "8.417",
        electronAffinityEv = "1.9", oxidationStates = "+4, +2",
        standardState = "Solid", meltingPointK = "527",
        boilingPointK = "1235", densityGPerCm3 = "9.32",
        category = "Metalloid", yearDiscovered = "1898",
        representativeMassNumber = 209,
    ),
    ElementProperties(
        atomicNumber = 85, symbol = "At", name = "Astatine",
        atomicMass = "209.98715", cpkHexColor = "754F45",
        electronConfiguration = "[Xe]6s2 4f14 5d10 6p5", electronegativity = "2.2",
        atomicRadiusPm = "202", ionizationEnergyEv = "9.5",
        electronAffinityEv = "2.8", oxidationStates = "7, 5, 3, 1, -1",
        standardState = "Solid", meltingPointK = "575",
        boilingPointK = "", densityGPerCm3 = "7",
        category = "Halogen", yearDiscovered = "1940",
        representativeMassNumber = 210,
    ),
    ElementProperties(
        atomicNumber = 86, symbol = "Rn", name = "Radon",
        atomicMass = "222.01758", cpkHexColor = "428296",
        electronConfiguration = "[Xe]6s2 4f14 5d10 6p6", electronegativity = "",
        atomicRadiusPm = "220", ionizationEnergyEv = "10.745",
        electronAffinityEv = "", oxidationStates = "0",
        standardState = "Gas", meltingPointK = "202",
        boilingPointK = "211.45", densityGPerCm3 = "0.00973",
        category = "Noble gas", yearDiscovered = "1900",
        representativeMassNumber = 222,
    ),
    ElementProperties(
        atomicNumber = 87, symbol = "Fr", name = "Francium",
        atomicMass = "223.01973", cpkHexColor = "420066",
        electronConfiguration = "[Rn]7s1", electronegativity = "0.7",
        atomicRadiusPm = "348", ionizationEnergyEv = "3.9",
        electronAffinityEv = "0.47", oxidationStates = "+1",
        standardState = "Solid", meltingPointK = "300",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Alkali metal", yearDiscovered = "1939",
        representativeMassNumber = 223,
    ),
    ElementProperties(
        atomicNumber = 88, symbol = "Ra", name = "Radium",
        atomicMass = "226.02541", cpkHexColor = "007D00",
        electronConfiguration = "[Rn]7s2", electronegativity = "0.9",
        atomicRadiusPm = "283", ionizationEnergyEv = "5.279",
        electronAffinityEv = "", oxidationStates = "+2",
        standardState = "Solid", meltingPointK = "973",
        boilingPointK = "1413", densityGPerCm3 = "5",
        category = "Alkaline earth metal", yearDiscovered = "1898",
        representativeMassNumber = 226,
    ),
    ElementProperties(
        atomicNumber = 89, symbol = "Ac", name = "Actinium",
        atomicMass = "227.02775", cpkHexColor = "70ABFA",
        electronConfiguration = "[Rn]7s2 6d1", electronegativity = "1.1",
        atomicRadiusPm = "260", ionizationEnergyEv = "5.17",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1324",
        boilingPointK = "3471", densityGPerCm3 = "10.07",
        category = "Actinide", yearDiscovered = "1899",
        representativeMassNumber = 227,
    ),
    ElementProperties(
        atomicNumber = 90, symbol = "Th", name = "Thorium",
        atomicMass = "232.038", cpkHexColor = "00BAFF",
        electronConfiguration = "[Rn]7s2 6d2", electronegativity = "1.3",
        atomicRadiusPm = "237", ionizationEnergyEv = "6.08",
        electronAffinityEv = "", oxidationStates = "+4",
        standardState = "Solid", meltingPointK = "2023",
        boilingPointK = "5061", densityGPerCm3 = "11.72",
        category = "Actinide", yearDiscovered = "1828",
        representativeMassNumber = 232,
    ),
    ElementProperties(
        atomicNumber = 91, symbol = "Pa", name = "Protactinium",
        atomicMass = "231.03588", cpkHexColor = "00A1FF",
        electronConfiguration = "[Rn]7s2 5f2 6d1", electronegativity = "1.5",
        atomicRadiusPm = "243", ionizationEnergyEv = "5.89",
        electronAffinityEv = "", oxidationStates = "+5, +4",
        standardState = "Solid", meltingPointK = "1845",
        boilingPointK = "", densityGPerCm3 = "15.37",
        category = "Actinide", yearDiscovered = "1913",
        representativeMassNumber = 231,
    ),
    ElementProperties(
        atomicNumber = 92, symbol = "U", name = "Uranium",
        atomicMass = "238.0289", cpkHexColor = "008FFF",
        electronConfiguration = "[Rn]7s2 5f3 6d1", electronegativity = "1.38",
        atomicRadiusPm = "240", ionizationEnergyEv = "6.194",
        electronAffinityEv = "", oxidationStates = "+6, +5, +4, +3",
        standardState = "Solid", meltingPointK = "1408",
        boilingPointK = "4404", densityGPerCm3 = "18.95",
        category = "Actinide", yearDiscovered = "1789",
        representativeMassNumber = 238,
    ),
    ElementProperties(
        atomicNumber = 93, symbol = "Np", name = "Neptunium",
        atomicMass = "237.048172", cpkHexColor = "0080FF",
        electronConfiguration = "[Rn]7s2 5f4 6d1", electronegativity = "1.36",
        atomicRadiusPm = "221", ionizationEnergyEv = "6.266",
        electronAffinityEv = "", oxidationStates = "+6, +5, +4, +3",
        standardState = "Solid", meltingPointK = "917",
        boilingPointK = "4175", densityGPerCm3 = "20.25",
        category = "Actinide", yearDiscovered = "1940",
        representativeMassNumber = 237,
    ),
    ElementProperties(
        atomicNumber = 94, symbol = "Pu", name = "Plutonium",
        atomicMass = "244.06420", cpkHexColor = "006BFF",
        electronConfiguration = "[Rn]7s2 5f6", electronegativity = "1.28",
        atomicRadiusPm = "243", ionizationEnergyEv = "6.06",
        electronAffinityEv = "", oxidationStates = "+6, +5, +4, +3",
        standardState = "Solid", meltingPointK = "913",
        boilingPointK = "3501", densityGPerCm3 = "19.84",
        category = "Actinide", yearDiscovered = "1940",
        representativeMassNumber = 244,
    ),
    ElementProperties(
        atomicNumber = 95, symbol = "Am", name = "Americium",
        atomicMass = "243.061380", cpkHexColor = "545CF2",
        electronConfiguration = "[Rn]7s2 5f7", electronegativity = "1.3",
        atomicRadiusPm = "244", ionizationEnergyEv = "5.993",
        electronAffinityEv = "", oxidationStates = "+6, +5, +4, +3",
        standardState = "Solid", meltingPointK = "1449",
        boilingPointK = "2284", densityGPerCm3 = "13.69",
        category = "Actinide", yearDiscovered = "1944",
        representativeMassNumber = 243,
    ),
    ElementProperties(
        atomicNumber = 96, symbol = "Cm", name = "Curium",
        atomicMass = "247.07035", cpkHexColor = "785CE3",
        electronConfiguration = "[Rn]7s2 5f7 6d1", electronegativity = "1.3",
        atomicRadiusPm = "245", ionizationEnergyEv = "6.02",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1618",
        boilingPointK = "3400", densityGPerCm3 = "13.51",
        category = "Actinide", yearDiscovered = "1944",
        representativeMassNumber = 247,
    ),
    ElementProperties(
        atomicNumber = 97, symbol = "Bk", name = "Berkelium",
        atomicMass = "247.07031", cpkHexColor = "8A4FE3",
        electronConfiguration = "[Rn]7s2 5f9", electronegativity = "1.3",
        atomicRadiusPm = "244", ionizationEnergyEv = "6.23",
        electronAffinityEv = "", oxidationStates = "+4, +3",
        standardState = "Solid", meltingPointK = "1323",
        boilingPointK = "", densityGPerCm3 = "14",
        category = "Actinide", yearDiscovered = "1949",
        representativeMassNumber = 247,
    ),
    ElementProperties(
        atomicNumber = 98, symbol = "Cf", name = "Californium",
        atomicMass = "251.07959", cpkHexColor = "A136D4",
        electronConfiguration = "[Rn]7s2 5f10", electronegativity = "1.3",
        atomicRadiusPm = "245", ionizationEnergyEv = "6.30",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1173",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Actinide", yearDiscovered = "1950",
        representativeMassNumber = 251,
    ),
    ElementProperties(
        atomicNumber = 99, symbol = "Es", name = "Einsteinium",
        atomicMass = "252.0830", cpkHexColor = "B31FD4",
        electronConfiguration = "[Rn]7s2 5f11", electronegativity = "1.3",
        atomicRadiusPm = "245", ionizationEnergyEv = "6.42",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1133",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Actinide", yearDiscovered = "1952",
        representativeMassNumber = 252,
    ),
    ElementProperties(
        atomicNumber = 100, symbol = "Fm", name = "Fermium",
        atomicMass = "257.09511", cpkHexColor = "B31FBA",
        electronConfiguration = "[Rn] 5f12 7s2", electronegativity = "1.3",
        atomicRadiusPm = "", ionizationEnergyEv = "6.50",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1800",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Actinide", yearDiscovered = "1952",
        representativeMassNumber = 257,
    ),
    ElementProperties(
        atomicNumber = 101, symbol = "Md", name = "Mendelevium",
        atomicMass = "258.09843", cpkHexColor = "B30DA6",
        electronConfiguration = "[Rn]7s2 5f13", electronegativity = "1.3",
        atomicRadiusPm = "", ionizationEnergyEv = "6.58",
        electronAffinityEv = "", oxidationStates = "+3, +2",
        standardState = "Solid", meltingPointK = "1100",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Actinide", yearDiscovered = "1955",
        representativeMassNumber = 258,
    ),
    ElementProperties(
        atomicNumber = 102, symbol = "No", name = "Nobelium",
        atomicMass = "259.10100", cpkHexColor = "BD0D87",
        electronConfiguration = "[Rn]7s2 5f14", electronegativity = "1.3",
        atomicRadiusPm = "", ionizationEnergyEv = "6.65",
        electronAffinityEv = "", oxidationStates = "+3, +2",
        standardState = "Solid", meltingPointK = "1100",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Actinide", yearDiscovered = "1957",
        representativeMassNumber = 259,
    ),
    ElementProperties(
        atomicNumber = 103, symbol = "Lr", name = "Lawrencium",
        atomicMass = "266.120", cpkHexColor = "C70066",
        electronConfiguration = "[Rn]7s2 5f14 6d1", electronegativity = "1.3",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "+3",
        standardState = "Solid", meltingPointK = "1900",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Actinide", yearDiscovered = "1961",
        representativeMassNumber = 266,
    ),
    ElementProperties(
        atomicNumber = 104, symbol = "Rf", name = "Rutherfordium",
        atomicMass = "267.122", cpkHexColor = "CC0059",
        electronConfiguration = "[Rn]7s2 5f14 6d2", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "+4",
        standardState = "Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Transition metal", yearDiscovered = "1964",
        representativeMassNumber = 267,
    ),
    ElementProperties(
        atomicNumber = 105, symbol = "Db", name = "Dubnium",
        atomicMass = "268.126", cpkHexColor = "D1004F",
        electronConfiguration = "[Rn]7s2 5f14 6d3", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "5, 4, 3",
        standardState = "Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Transition metal", yearDiscovered = "1967",
        representativeMassNumber = 268,
    ),
    ElementProperties(
        atomicNumber = 106, symbol = "Sg", name = "Seaborgium",
        atomicMass = "269.128", cpkHexColor = "D90045",
        electronConfiguration = "[Rn]7s2 5f14 6d4", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "6, 5, 4, 3, 0",
        standardState = "Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Transition metal", yearDiscovered = "1974",
        representativeMassNumber = 269,
    ),
    ElementProperties(
        atomicNumber = 107, symbol = "Bh", name = "Bohrium",
        atomicMass = "270.133", cpkHexColor = "E00038",
        electronConfiguration = "[Rn]7s2 5f14 6d5", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "7, 5, 4, 3",
        standardState = "Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Transition metal", yearDiscovered = "1976",
        representativeMassNumber = 270,
    ),
    ElementProperties(
        atomicNumber = 108, symbol = "Hs", name = "Hassium",
        atomicMass = "269.1336", cpkHexColor = "E6002E",
        electronConfiguration = "[Rn]7s2 5f14 6d6", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "8, 6, 5, 4, 3, 2",
        standardState = "Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Transition metal", yearDiscovered = "1984",
        representativeMassNumber = 269,
    ),
    ElementProperties(
        atomicNumber = 109, symbol = "Mt", name = "Meitnerium",
        atomicMass = "277.154", cpkHexColor = "EB0026",
        electronConfiguration = "[Rn]7s2 5f14 6d7 (calculated)", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "9, 8, 6, 4, 3, 1",
        standardState = "Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Transition metal", yearDiscovered = "1982",
        representativeMassNumber = 277,
    ),
    ElementProperties(
        atomicNumber = 110, symbol = "Ds", name = "Darmstadtium",
        atomicMass = "282.166", cpkHexColor = "",
        electronConfiguration = "[Rn]7s2 5f14 6d8 (predicted)", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "8, 6, 4, 2, 0",
        standardState = "Expected to be a Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Transition metal", yearDiscovered = "1994",
        representativeMassNumber = 282,
    ),
    ElementProperties(
        atomicNumber = 111, symbol = "Rg", name = "Roentgenium",
        atomicMass = "282.169", cpkHexColor = "",
        electronConfiguration = "[Rn]7s2 5f14 6d9 (predicted)", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "5, 3, 1, -1",
        standardState = "Expected to be a Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Transition metal", yearDiscovered = "1994",
        representativeMassNumber = 282,
    ),
    ElementProperties(
        atomicNumber = 112, symbol = "Cn", name = "Copernicium",
        atomicMass = "286.179", cpkHexColor = "",
        electronConfiguration = "[Rn]7s2 5f14 6d10 (predicted)", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "2, 1, 0",
        standardState = "Expected to be a Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Transition metal", yearDiscovered = "1996",
        representativeMassNumber = 286,
    ),
    ElementProperties(
        atomicNumber = 113, symbol = "Nh", name = "Nihonium",
        atomicMass = "286.182", cpkHexColor = "",
        electronConfiguration = "[Rn]5f14 6d10 7s2 7p1 (predicted)", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "",
        standardState = "Expected to be a Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Post-transition metal", yearDiscovered = "2004",
        representativeMassNumber = 286,
    ),
    ElementProperties(
        atomicNumber = 114, symbol = "Fl", name = "Flerovium",
        atomicMass = "290.192", cpkHexColor = "",
        electronConfiguration = "[Rn]7s2 7p2 5f14 6d10 (predicted)", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "6, 4,2, 1, 0",
        standardState = "Expected to be a Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Post-transition metal", yearDiscovered = "1998",
        representativeMassNumber = 290,
    ),
    ElementProperties(
        atomicNumber = 115, symbol = "Mc", name = "Moscovium",
        atomicMass = "290.196", cpkHexColor = "",
        electronConfiguration = "[Rn]7s2 7p3 5f14 6d10 (predicted)", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "3, 1",
        standardState = "Expected to be a Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Post-transition metal", yearDiscovered = "2003",
        representativeMassNumber = 290,
    ),
    ElementProperties(
        atomicNumber = 116, symbol = "Lv", name = "Livermorium",
        atomicMass = "293.205", cpkHexColor = "",
        electronConfiguration = "[Rn]7s2 7p4 5f14 6d10 (predicted)", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "+4, +2, -2",
        standardState = "Expected to be a Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Post-transition metal", yearDiscovered = "2000",
        representativeMassNumber = 293,
    ),
    ElementProperties(
        atomicNumber = 117, symbol = "Ts", name = "Tennessine",
        atomicMass = "294.211", cpkHexColor = "",
        electronConfiguration = "[Rn]7s2 7p5 5f14 6d10 (predicted)", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "+5, +3, +1, -1",
        standardState = "Expected to be a Solid", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Halogen", yearDiscovered = "2010",
        representativeMassNumber = 294,
    ),
    ElementProperties(
        atomicNumber = 118, symbol = "Og", name = "Oganesson",
        atomicMass = "295.216", cpkHexColor = "",
        electronConfiguration = "[Rn]7s2 7p6 5f14 6d10 (predicted)", electronegativity = "",
        atomicRadiusPm = "", ionizationEnergyEv = "",
        electronAffinityEv = "", oxidationStates = "+6, +4, +2, +1, 0, -1",
        standardState = "Expected to be a Gas", meltingPointK = "",
        boilingPointK = "", densityGPerCm3 = "",
        category = "Noble gas", yearDiscovered = "2006",
        representativeMassNumber = 295,
    )
)

internal fun elementByAtomicNumber(number: Int): ElementProperties =
    ELEMENTS[(number.coerceIn(1, 118)) - 1]
