import {StyleSheet} from 'react-native';
export default StyleSheet.create({
root:{flex:1,backgroundColor:'#020611'},safe:{flex:1},screen:{flex:1,backgroundColor:'#020611'},
header:{height:88,paddingHorizontal:26,paddingVertical:10,borderBottomWidth:1,borderColor:'#214969',backgroundColor:'#050d1c',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},
title:{fontSize:34,fontWeight:'900',color:'#f5fbff',letterSpacing:5,textShadowColor:'#2a9fe8',textShadowRadius:14},sub:{color:'#79d7ff',fontSize:11,letterSpacing:2.5,marginTop:2},
headerBadge:{width:80,height:58,borderRadius:12,borderWidth:1,borderColor:'#2d8fc4',backgroundColor:'#0a1b31',alignItems:'center',justifyContent:'center'},headerBadgeTop:{fontSize:24,fontWeight:'900',color:'#ffd166'},headerBadgeBottom:{fontSize:8,letterSpacing:1.5,color:'#a9dff7'},
tableScroll:{alignItems:'center',paddingVertical:8},tableStage:{position:'relative',overflow:'hidden',backgroundColor:'#030a17'},museumGlow:{position:'absolute',left:'15%',right:'15%',top:0,height:220,borderRadius:999,backgroundColor:'#0a2e52',opacity:.38,transform:[{scaleX:2.2}]},
tile:{position:'absolute',borderRadius:9,borderWidth:1.3,padding:5,backgroundColor:'#0b1a2d',overflow:'hidden',elevation:8,shadowOpacity:.62,shadowRadius:8,shadowOffset:{width:0,height:4},transform:[{perspective:700},{rotateX:'8deg'}]},tileGlow:{position:'absolute',left:0,right:0,top:0,height:5,opacity:.9},num:{fontSize:9,color:'#c8e8f9'},sym:{fontSize:24,fontWeight:'900',color:'#fff',textAlign:'center',lineHeight:30,textShadowColor:'#000',textShadowRadius:4},name:{fontSize:8,color:'#b9d4e6',textAlign:'center'},seriesLabel:{position:'absolute',width:140,color:'#627f97',fontSize:9,fontWeight:'800',letterSpacing:1.2},
footerBar:{height:38,paddingHorizontal:22,backgroundColor:'#050d1c',borderTopWidth:1,borderColor:'#173a57',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},hint:{color:'#7ca8c4',fontSize:10,letterSpacing:1.1},version:{color:'#ffd166',fontSize:9,fontWeight:'800',letterSpacing:1.2},
detail:{flexGrow:1,flexDirection:'row',padding:18,gap:16,backgroundColor:'#020611'},panel:{flex:1,borderWidth:1,borderColor:'#285d88',borderRadius:18,padding:18,backgroundColor:'#071326e8'},big:{fontSize:38,fontWeight:'900',color:'#fff'},gold:{color:'#ffd166'},fact:{color:'#d9efff',fontSize:15,marginTop:8},back:{color:'#70d8ff',fontSize:16,fontWeight:'800',marginBottom:10},bond:{marginTop:16,padding:13,borderRadius:12,backgroundColor:'#112b47'},bondText:{color:'#fff',fontSize:15,marginTop:5},familyPill:{alignSelf:'flex-start',paddingHorizontal:12,paddingVertical:5,borderRadius:999,marginVertical:10},familyText:{color:'#fff',fontSize:11,fontWeight:'900',letterSpacing:1},journey:{flexDirection:'row',gap:8,marginTop:14},journeyNode:{flex:1,padding:9,borderRadius:10,borderWidth:1,borderColor:'#315e83',backgroundColor:'#0b1b31',alignItems:'center'},journeyTitle:{fontSize:10,fontWeight:'900',color:'#ffd166'},journeyScale:{fontSize:8,color:'#8ccbe8',marginTop:3},aiButton:{marginTop:14,padding:12,borderRadius:12,borderWidth:1,borderColor:'#43bffc',backgroundColor:'#0b2a45'},aiButtonTitle:{color:'#fff',fontWeight:'900',fontSize:14},aiButtonText:{color:'#91cfe9',fontSize:10,marginTop:3}
});
